# Generated by Django 5.1 on 2024-08-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo0', models.CharField(max_length=255, verbose_name='Nome')),
                ('campo1', models.CharField(max_length=255, verbose_name='Estado')),
                ('campo2', models.CharField(max_length=255, verbose_name='País')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
