# Generated by Django 5.1 on 2024-08-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=255, verbose_name='Console')),
                ('campo2', models.CharField(max_length=255, verbose_name='Jogo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
